In [34]:
import pandas as pd
import sqlite3

# 데이터베이스 파일 경로
db_file = 'btc_data_m15_20170901_20241205.db'

# 데이터베이스 연결
con = sqlite3.connect(db_file)

# SQL 쿼리 실행 및 데이터프레임으로 불러오기
query = "SELECT * FROM ticker_data"
df = pd.read_sql_query(query, con)

# 데이터베이스 연결 종료
con.close()

# 데이터프레임 출력
df.head()  # 데이터프레임의 첫 5행 출력

,type,code,opening_price,high_price,low_price,trade_price,trade_volume,trade_date,trade_time,trade_timestamp
0,ticker,KRW-BTC,4362000.0,4371000.0,4356000.0,4369000.0,0.083938,2017-09-26,17:45,1506447900
1,ticker,KRW-BTC,4369000.0,4372000.0,4363000.0,4363000.0,0.027614,2017-09-26,18:00,1506448800
2,ticker,KRW-BTC,4363000.0,4367000.0,4351000.0,4359000.0,0.037781,2017-09-26,18:15,1506449700
3,ticker,KRW-BTC,4359000.0,4362000.0,4353000.0,4353000.0,0.039355,2017-09-26,18:30,1506450600
4,ticker,KRW-BTC,4355000.0,4368000.0,4352000.0,4363000.0,0.343634,2017-09-26,18:45,1506451500

In [35]:
df

,type,code,opening_price,high_price,low_price,trade_price,trade_volume,trade_date,trade_time,trade_timestamp
0,ticker,KRW-BTC,4362000.0,4371000.0,4356000.0,4369000.0,0.083938,2017-09-26,17:45,1506447900
1,ticker,KRW-BTC,4369000.0,4372000.0,4363000.0,4363000.0,0.027614,2017-09-26,18:00,1506448800
2,ticker,KRW-BTC,4363000.0,4367000.0,4351000.0,4359000.0,0.037781,2017-09-26,18:15,1506449700
3,ticker,KRW-BTC,4359000.0,4362000.0,4353000.0,4353000.0,0.039355,2017-09-26,18:30,1506450600
4,ticker,KRW-BTC,4355000.0,4368000.0,4352000.0,4363000.0,0.343634,2017-09-26,18:45,1506451500
...,...,...,...,...,...,...,...,...,...,...
1234952,ticker,KRW-BTC,134622000.0,134668000.0,134230000.0,134668000.0,50.700497,2024-12-04,22:45,1733352300
1234953,ticker,KRW-BTC,134667000.0,134834000.0,134270000.0,134397000.0,46.649826,2024-12-04,23:00,1733353200
1234954,ticker,KRW-BTC,134301000.0,134846000.0,134270000.0,134842000.0,36.591862,2024-12-04,23:15,1733354100
1234955,ticker,KRW-BTC,134833000.0,135304000.0,134702000.0,135105000.0,84.316044,2024-12-04,23:30,1733355000
1234956,ticker,KRW-BTC,135088000.0,135177000.0,134705000.0,134707000.0,64.862375,2024-12-04,23:45,1733355900

In [36]:
df = df.drop_duplicates(keep='first')
df

,type,code,opening_price,high_price,low_price,trade_price,trade_volume,trade_date,trade_time,trade_timestamp
0,ticker,KRW-BTC,4362000.0,4371000.0,4356000.0,4369000.0,0.083938,2017-09-26,17:45,1506447900
1,ticker,KRW-BTC,4369000.0,4372000.0,4363000.0,4363000.0,0.027614,2017-09-26,18:00,1506448800
2,ticker,KRW-BTC,4363000.0,4367000.0,4351000.0,4359000.0,0.037781,2017-09-26,18:15,1506449700
3,ticker,KRW-BTC,4359000.0,4362000.0,4353000.0,4353000.0,0.039355,2017-09-26,18:30,1506450600
4,ticker,KRW-BTC,4355000.0,4368000.0,4352000.0,4363000.0,0.343634,2017-09-26,18:45,1506451500
...,...,...,...,...,...,...,...,...,...,...
1234858,ticker,KRW-BTC,134622000.0,134668000.0,134230000.0,134668000.0,50.700497,2024-12-04,22:45,1733352300
1234859,ticker,KRW-BTC,134667000.0,134834000.0,134270000.0,134397000.0,46.649826,2024-12-04,23:00,1733353200
1234860,ticker,KRW-BTC,134301000.0,134846000.0,134270000.0,134842000.0,36.591862,2024-12-04,23:15,1733354100
1234955,ticker,KRW-BTC,134833000.0,135304000.0,134702000.0,135105000.0,84.316044,2024-12-04,23:30,1733355000
1234956,ticker,KRW-BTC,135088000.0,135177000.0,134705000.0,134707000.0,64.862375,2024-12-04,23:45,1733355900

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 251423 entries, 0 to 1234956
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   type             251423 non-null  object
 1   code             251423 non-null  object
 2   opening_price    251423 non-null  float64
 3   high_price       251423 non-null  float64
 4   low_price        251423 non-null  float64
 5   trade_price      251423 non-null  float64
 6   trade_volume     251423 non-null  float64
 7   trade_date       251423 non-null  object
 8   trade_time       251423 non-null  object
 9   trade_timestamp  251423 non-null  int64
dtypes: float64(5), int64(1), object(4)
memory usage: 21.1+ MB

In [38]:
# trade_date와 trade_time을 결합하여 새로운 datetime 컬럼 생성
df['datetime'] = pd.to_datetime(df['trade_date'] + ' ' + df['trade_time'])

# 결과 출력
df.head()

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_14280\2044120202.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['datetime'] = pd.to_datetime(df['trade_date'] + ' ' + df['trade_time'])

,type,code,opening_price,high_price,low_price,trade_price,trade_volume,trade_date,trade_time,trade_timestamp,datetime
0,ticker,KRW-BTC,4362000.0,4371000.0,4356000.0,4369000.0,0.083938,2017-09-26,17:45,1506447900,2017-09-26 17:45:00
1,ticker,KRW-BTC,4369000.0,4372000.0,4363000.0,4363000.0,0.027614,2017-09-26,18:00,1506448800,2017-09-26 18:00:00
2,ticker,KRW-BTC,4363000.0,4367000.0,4351000.0,4359000.0,0.037781,2017-09-26,18:15,1506449700,2017-09-26 18:15:00
3,ticker,KRW-BTC,4359000.0,4362000.0,4353000.0,4353000.0,0.039355,2017-09-26,18:30,1506450600,2017-09-26 18:30:00
4,ticker,KRW-BTC,4355000.0,4368000.0,4352000.0,4363000.0,0.343634,2017-09-26,18:45,1506451500,2017-09-26 18:45:00

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 251423 entries, 0 to 1234956
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   type             251423 non-null  object
 1   code             251423 non-null  object
 2   opening_price    251423 non-null  float64
 3   high_price       251423 non-null  float64
 4   low_price        251423 non-null  float64
 5   trade_price      251423 non-null  float64
 6   trade_volume     251423 non-null  float64
 7   trade_date       251423 non-null  object
 8   trade_time       251423 non-null  object
 9   trade_timestamp  251423 non-null  int64
 10  datetime         251423 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(1), object(4)
memory usage: 23.0+ MB

In [40]:
df_sorted = df.sort_values(by='datetime')
df_sorted

,type,code,opening_price,high_price,low_price,trade_price,trade_volume,trade_date,trade_time,trade_timestamp,datetime
0,ticker,KRW-BTC,4362000.0,4371000.0,4356000.0,4369000.0,0.083938,2017-09-26,17:45,1506447900,2017-09-26 17:45:00
1,ticker,KRW-BTC,4369000.0,4372000.0,4363000.0,4363000.0,0.027614,2017-09-26,18:00,1506448800,2017-09-26 18:00:00
2,ticker,KRW-BTC,4363000.0,4367000.0,4351000.0,4359000.0,0.037781,2017-09-26,18:15,1506449700,2017-09-26 18:15:00
3,ticker,KRW-BTC,4359000.0,4362000.0,4353000.0,4353000.0,0.039355,2017-09-26,18:30,1506450600,2017-09-26 18:30:00
4,ticker,KRW-BTC,4355000.0,4368000.0,4352000.0,4363000.0,0.343634,2017-09-26,18:45,1506451500,2017-09-26 18:45:00
...,...,...,...,...,...,...,...,...,...,...,...
1234858,ticker,KRW-BTC,134622000.0,134668000.0,134230000.0,134668000.0,50.700497,2024-12-04,22:45,1733352300,2024-12-04 22:45:00
1234859,ticker,KRW-BTC,134667000.0,134834000.0,134270000.0,134397000.0,46.649826,2024-12-04,23:00,1733353200,2024-12-04 23:00:00
1234860,ticker,KRW-BTC,134301000.0,134846000.0,134270000.0,134842000.0,36.591862,2024-12-04,23:15,1733354100,2024-12-04 23:15:00
1234955,ticker,KRW-BTC,134833000.0,135304000.0,134702000.0,135105000.0,84.316044,2024-12-04,23:30,1733355000,2024-12-04 23:30:00
1234956,ticker,KRW-BTC,135088000.0,135177000.0,134705000.0,134707000.0,64.862375,2024-12-04,23:45,1733355900,2024-12-04 23:45:00

In [41]:
import sqlite3

# SQLite 데이터베이스 파일 경로
db_file = "btc_data_m15_sorted.db"

# 데이터베이스 연결
con = sqlite3.connect(db_file)

# 데이터프레임을 SQLite 데이터베이스에 저장
df_sorted.to_sql(name='ticker_data', con=con, if_exists='replace', index=False)

# 연결 종료
con.close()

print("데이터프레임이 SQLite 데이터베이스에 저장되었습니다.")

데이터프레임이 SQLite 데이터베이스에 저장되었습니다.

In [42]:
df = df_sorted
df

,type,code,opening_price,high_price,low_price,trade_price,trade_volume,trade_date,trade_time,trade_timestamp,datetime
0,ticker,KRW-BTC,4362000.0,4371000.0,4356000.0,4369000.0,0.083938,2017-09-26,17:45,1506447900,2017-09-26 17:45:00
1,ticker,KRW-BTC,4369000.0,4372000.0,4363000.0,4363000.0,0.027614,2017-09-26,18:00,1506448800,2017-09-26 18:00:00
2,ticker,KRW-BTC,4363000.0,4367000.0,4351000.0,4359000.0,0.037781,2017-09-26,18:15,1506449700,2017-09-26 18:15:00
3,ticker,KRW-BTC,4359000.0,4362000.0,4353000.0,4353000.0,0.039355,2017-09-26,18:30,1506450600,2017-09-26 18:30:00
4,ticker,KRW-BTC,4355000.0,4368000.0,4352000.0,4363000.0,0.343634,2017-09-26,18:45,1506451500,2017-09-26 18:45:00
...,...,...,...,...,...,...,...,...,...,...,...
1234858,ticker,KRW-BTC,134622000.0,134668000.0,134230000.0,134668000.0,50.700497,2024-12-04,22:45,1733352300,2024-12-04 22:45:00
1234859,ticker,KRW-BTC,134667000.0,134834000.0,134270000.0,134397000.0,46.649826,2024-12-04,23:00,1733353200,2024-12-04 23:00:00
1234860,ticker,KRW-BTC,134301000.0,134846000.0,134270000.0,134842000.0,36.591862,2024-12-04,23:15,1733354100,2024-12-04 23:15:00
1234955,ticker,KRW-BTC,134833000.0,135304000.0,134702000.0,135105000.0,84.316044,2024-12-04,23:30,1733355000,2024-12-04 23:30:00
1234956,ticker,KRW-BTC,135088000.0,135177000.0,134705000.0,134707000.0,64.862375,2024-12-04,23:45,1733355900,2024-12-04 23:45:00

In [43]:
df['volatility'] = df['high_price'] - df['low_price']

In [44]:
df

,type,code,opening_price,high_price,low_price,trade_price,trade_volume,trade_date,trade_time,trade_timestamp,datetime,volatility
0,ticker,KRW-BTC,4362000.0,4371000.0,4356000.0,4369000.0,0.083938,2017-09-26,17:45,1506447900,2017-09-26 17:45:00,15000.0
1,ticker,KRW-BTC,4369000.0,4372000.0,4363000.0,4363000.0,0.027614,2017-09-26,18:00,1506448800,2017-09-26 18:00:00,9000.0
2,ticker,KRW-BTC,4363000.0,4367000.0,4351000.0,4359000.0,0.037781,2017-09-26,18:15,1506449700,2017-09-26 18:15:00,16000.0
3,ticker,KRW-BTC,4359000.0,4362000.0,4353000.0,4353000.0,0.039355,2017-09-26,18:30,1506450600,2017-09-26 18:30:00,9000.0
4,ticker,KRW-BTC,4355000.0,4368000.0,4352000.0,4363000.0,0.343634,2017-09-26,18:45,1506451500,2017-09-26 18:45:00,16000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1234858,ticker,KRW-BTC,134622000.0,134668000.0,134230000.0,134668000.0,50.700497,2024-12-04,22:45,1733352300,2024-12-04 22:45:00,438000.0
1234859,ticker,KRW-BTC,134667000.0,134834000.0,134270000.0,134397000.0,46.649826,2024-12-04,23:00,1733353200,2024-12-04 23:00:00,564000.0
1234860,ticker,KRW-BTC,134301000.0,134846000.0,134270000.0,134842000.0,36.591862,2024-12-04,23:15,1733354100,2024-12-04 23:15:00,576000.0
1234955,ticker,KRW-BTC,134833000.0,135304000.0,134702000.0,135105000.0,84.316044,2024-12-04,23:30,1733355000,2024-12-04 23:30:00,602000.0
1234956,ticker,KRW-BTC,135088000.0,135177000.0,134705000.0,134707000.0,64.862375,2024-12-04,23:45,1733355900,2024-12-04 23:45:00,472000.0

In [45]:
df['hour'] = df['datetime'].dt.hour
df['minute'] = df['datetime'].dt.minute
df

,type,code,opening_price,high_price,low_price,trade_price,trade_volume,trade_date,trade_time,trade_timestamp,datetime,volatility,hour,minute
0,ticker,KRW-BTC,4362000.0,4371000.0,4356000.0,4369000.0,0.083938,2017-09-26,17:45,1506447900,2017-09-26 17:45:00,15000.0,17,45
1,ticker,KRW-BTC,4369000.0,4372000.0,4363000.0,4363000.0,0.027614,2017-09-26,18:00,1506448800,2017-09-26 18:00:00,9000.0,18,0
2,ticker,KRW-BTC,4363000.0,4367000.0,4351000.0,4359000.0,0.037781,2017-09-26,18:15,1506449700,2017-09-26 18:15:00,16000.0,18,15
3,ticker,KRW-BTC,4359000.0,4362000.0,4353000.0,4353000.0,0.039355,2017-09-26,18:30,1506450600,2017-09-26 18:30:00,9000.0,18,30
4,ticker,KRW-BTC,4355000.0,4368000.0,4352000.0,4363000.0,0.343634,2017-09-26,18:45,1506451500,2017-09-26 18:45:00,16000.0,18,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1234858,ticker,KRW-BTC,134622000.0,134668000.0,134230000.0,134668000.0,50.700497,2024-12-04,22:45,1733352300,2024-12-04 22:45:00,438000.0,22,45
1234859,ticker,KRW-BTC,134667000.0,134834000.0,134270000.0,134397000.0,46.649826,2024-12-04,23:00,1733353200,2024-12-04 23:00:00,564000.0,23,0
1234860,ticker,KRW-BTC,134301000.0,134846000.0,134270000.0,134842000.0,36.591862,2024-12-04,23:15,1733354100,2024-12-04 23:15:00,576000.0,23,15
1234955,ticker,KRW-BTC,134833000.0,135304000.0,134702000.0,135105000.0,84.316044,2024-12-04,23:30,1733355000,2024-12-04 23:30:00,602000.0,23,30
1234956,ticker,KRW-BTC,135088000.0,135177000.0,134705000.0,134707000.0,64.862375,2024-12-04,23:45,1733355900,2024-12-04 23:45:00,472000.0,23,45

In [46]:
# 다음 봉의 상승률 계산
df['next_return'] = df['trade_price'].shift(-1) / df['trade_price'] - 1

# 변동성 돌파 성공률 계산
df['target'] = df['opening_price'] + (df['high_price'].shift(1) - df['low_price'].shift(1)) * 0.5
df['success'] = (df['high_price'] > df['target']).astype(int)
df

,type,code,opening_price,high_price,low_price,trade_price,trade_volume,trade_date,trade_time,trade_timestamp,datetime,volatility,hour,minute,next_return,target,success
0,ticker,KRW-BTC,4362000.0,4371000.0,4356000.0,4369000.0,0.083938,2017-09-26,17:45,1506447900,2017-09-26 17:45:00,15000.0,17,45,-0.001373,NaN,0
1,ticker,KRW-BTC,4369000.0,4372000.0,4363000.0,4363000.0,0.027614,2017-09-26,18:00,1506448800,2017-09-26 18:00:00,9000.0,18,0,-0.000917,4376500.0,0
2,ticker,KRW-BTC,4363000.0,4367000.0,4351000.0,4359000.0,0.037781,2017-09-26,18:15,1506449700,2017-09-26 18:15:00,16000.0,18,15,-0.001376,4367500.0,0
3,ticker,KRW-BTC,4359000.0,4362000.0,4353000.0,4353000.0,0.039355,2017-09-26,18:30,1506450600,2017-09-26 18:30:00,9000.0,18,30,0.002297,4367000.0,0
4,ticker,KRW-BTC,4355000.0,4368000.0,4352000.0,4363000.0,0.343634,2017-09-26,18:45,1506451500,2017-09-26 18:45:00,16000.0,18,45,0.002521,4359500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1234858,ticker,KRW-BTC,134622000.0,134668000.0,134230000.0,134668000.0,50.700497,2024-12-04,22:45,1733352300,2024-12-04 22:45:00,438000.0,22,45,-0.002012,134827000.0,0
1234859,ticker,KRW-BTC,134667000.0,134834000.0,134270000.0,134397000.0,46.649826,2024-12-04,23:00,1733353200,2024-12-04 23:00:00,564000.0,23,0,0.003311,134886000.0,0
1234860,ticker,KRW-BTC,134301000.0,134846000.0,134270000.0,134842000.0,36.591862,2024-12-04,23:15,1733354100,2024-12-04 23:15:00,576000.0,23,15,0.001950,134583000.0,1
1234955,ticker,KRW-BTC,134833000.0,135304000.0,134702000.0,135105000.0,84.316044,2024-12-04,23:30,1733355000,2024-12-04 23:30:00,602000.0,23,30,-0.002946,135121000.0,1
1234956,ticker,KRW-BTC,135088000.0,135177000.0,134705000.0,134707000.0,64.862375,2024-12-04,23:45,1733355900,2024-12-04 23:45:00,472000.0,23,45,NaN,135389000.0,0

In [47]:
df.rename(columns={'trade_price':'closing_price'}, inplace=True)
df

,type,code,opening_price,high_price,low_price,closing_price,trade_volume,trade_date,trade_time,trade_timestamp,datetime,volatility,hour,minute,next_return,target,success
0,ticker,KRW-BTC,4362000.0,4371000.0,4356000.0,4369000.0,0.083938,2017-09-26,17:45,1506447900,2017-09-26 17:45:00,15000.0,17,45,-0.001373,NaN,0
1,ticker,KRW-BTC,4369000.0,4372000.0,4363000.0,4363000.0,0.027614,2017-09-26,18:00,1506448800,2017-09-26 18:00:00,9000.0,18,0,-0.000917,4376500.0,0
2,ticker,KRW-BTC,4363000.0,4367000.0,4351000.0,4359000.0,0.037781,2017-09-26,18:15,1506449700,2017-09-26 18:15:00,16000.0,18,15,-0.001376,4367500.0,0
3,ticker,KRW-BTC,4359000.0,4362000.0,4353000.0,4353000.0,0.039355,2017-09-26,18:30,1506450600,2017-09-26 18:30:00,9000.0,18,30,0.002297,4367000.0,0
4,ticker,KRW-BTC,4355000.0,4368000.0,4352000.0,4363000.0,0.343634,2017-09-26,18:45,1506451500,2017-09-26 18:45:00,16000.0,18,45,0.002521,4359500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1234858,ticker,KRW-BTC,134622000.0,134668000.0,134230000.0,134668000.0,50.700497,2024-12-04,22:45,1733352300,2024-12-04 22:45:00,438000.0,22,45,-0.002012,134827000.0,0
1234859,ticker,KRW-BTC,134667000.0,134834000.0,134270000.0,134397000.0,46.649826,2024-12-04,23:00,1733353200,2024-12-04 23:00:00,564000.0,23,0,0.003311,134886000.0,0
1234860,ticker,KRW-BTC,134301000.0,134846000.0,134270000.0,134842000.0,36.591862,2024-12-04,23:15,1733354100,2024-12-04 23:15:00,576000.0,23,15,0.001950,134583000.0,1
1234955,ticker,KRW-BTC,134833000.0,135304000.0,134702000.0,135105000.0,84.316044,2024-12-04,23:30,1733355000,2024-12-04 23:30:00,602000.0,23,30,-0.002946,135121000.0,1
1234956,ticker,KRW-BTC,135088000.0,135177000.0,134705000.0,134707000.0,64.862375,2024-12-04,23:45,1733355900,2024-12-04 23:45:00,472000.0,23,45,NaN,135389000.0,0

In [48]:
new_column_order = [
    'datetime', 'type', 'code', 'opening_price', 'closing_price', 'high_price', 'low_price', 'trade_volume', 'volatility', 'next_return', 'target', 'success', 'trade_date', 'trade_time', 'hour', 'minute', 'trade_timestamp', 
]

df = df[new_column_order] 
df

,datetime,type,code,opening_price,closing_price,high_price,low_price,trade_volume,volatility,next_return,target,success,trade_date,trade_time,hour,minute,trade_timestamp
0,2017-09-26 17:45:00,ticker,KRW-BTC,4362000.0,4369000.0,4371000.0,4356000.0,0.083938,15000.0,-0.001373,NaN,0,2017-09-26,17:45,17,45,1506447900
1,2017-09-26 18:00:00,ticker,KRW-BTC,4369000.0,4363000.0,4372000.0,4363000.0,0.027614,9000.0,-0.000917,4376500.0,0,2017-09-26,18:00,18,0,1506448800
2,2017-09-26 18:15:00,ticker,KRW-BTC,4363000.0,4359000.0,4367000.0,4351000.0,0.037781,16000.0,-0.001376,4367500.0,0,2017-09-26,18:15,18,15,1506449700
3,2017-09-26 18:30:00,ticker,KRW-BTC,4359000.0,4353000.0,4362000.0,4353000.0,0.039355,9000.0,0.002297,4367000.0,0,2017-09-26,18:30,18,30,1506450600
4,2017-09-26 18:45:00,ticker,KRW-BTC,4355000.0,4363000.0,4368000.0,4352000.0,0.343634,16000.0,0.002521,4359500.0,1,2017-09-26,18:45,18,45,1506451500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1234858,2024-12-04 22:45:00,ticker,KRW-BTC,134622000.0,134668000.0,134668000.0,134230000.0,50.700497,438000.0,-0.002012,134827000.0,0,2024-12-04,22:45,22,45,1733352300
1234859,2024-12-04 23:00:00,ticker,KRW-BTC,134667000.0,134397000.0,134834000.0,134270000.0,46.649826,564000.0,0.003311,134886000.0,0,2024-12-04,23:00,23,0,1733353200
1234860,2024-12-04 23:15:00,ticker,KRW-BTC,134301000.0,134842000.0,134846000.0,134270000.0,36.591862,576000.0,0.001950,134583000.0,1,2024-12-04,23:15,23,15,1733354100
1234955,2024-12-04 23:30:00,ticker,KRW-BTC,134833000.0,135105000.0,135304000.0,134702000.0,84.316044,602000.0,-0.002946,135121000.0,1,2024-12-04,23:30,23,30,1733355000
1234956,2024-12-04 23:45:00,ticker,KRW-BTC,135088000.0,134707000.0,135177000.0,134705000.0,64.862375,472000.0,NaN,135389000.0,0,2024-12-04,23:45,23,45,1733355900

In [49]:
df.reset_index(drop=True, inplace=True)
df

,datetime,type,code,opening_price,closing_price,high_price,low_price,trade_volume,volatility,next_return,target,success,trade_date,trade_time,hour,minute,trade_timestamp
0,2017-09-26 17:45:00,ticker,KRW-BTC,4362000.0,4369000.0,4371000.0,4356000.0,0.083938,15000.0,-0.001373,NaN,0,2017-09-26,17:45,17,45,1506447900
1,2017-09-26 18:00:00,ticker,KRW-BTC,4369000.0,4363000.0,4372000.0,4363000.0,0.027614,9000.0,-0.000917,4376500.0,0,2017-09-26,18:00,18,0,1506448800
2,2017-09-26 18:15:00,ticker,KRW-BTC,4363000.0,4359000.0,4367000.0,4351000.0,0.037781,16000.0,-0.001376,4367500.0,0,2017-09-26,18:15,18,15,1506449700
3,2017-09-26 18:30:00,ticker,KRW-BTC,4359000.0,4353000.0,4362000.0,4353000.0,0.039355,9000.0,0.002297,4367000.0,0,2017-09-26,18:30,18,30,1506450600
4,2017-09-26 18:45:00,ticker,KRW-BTC,4355000.0,4363000.0,4368000.0,4352000.0,0.343634,16000.0,0.002521,4359500.0,1,2017-09-26,18:45,18,45,1506451500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251418,2024-12-04 22:45:00,ticker,KRW-BTC,134622000.0,134668000.0,134668000.0,134230000.0,50.700497,438000.0,-0.002012,134827000.0,0,2024-12-04,22:45,22,45,1733352300
251419,2024-12-04 23:00:00,ticker,KRW-BTC,134667000.0,134397000.0,134834000.0,134270000.0,46.649826,564000.0,0.003311,134886000.0,0,2024-12-04,23:00,23,0,1733353200
251420,2024-12-04 23:15:00,ticker,KRW-BTC,134301000.0,134842000.0,134846000.0,134270000.0,36.591862,576000.0,0.001950,134583000.0,1,2024-12-04,23:15,23,15,1733354100
251421,2024-12-04 23:30:00,ticker,KRW-BTC,134833000.0,135105000.0,135304000.0,134702000.0,84.316044,602000.0,-0.002946,135121000.0,1,2024-12-04,23:30,23,30,1733355000
251422,2024-12-04 23:45:00,ticker,KRW-BTC,135088000.0,134707000.0,135177000.0,134705000.0,64.862375,472000.0,NaN,135389000.0,0,2024-12-04,23:45,23,45,1733355900

In [51]:
import sqlite3

# SQLite 데이터베이스 파일 경로
db_file = "btc_data_m15_preprocessing_ex.db"

# 데이터베이스 연결
con = sqlite3.connect(db_file)

# 데이터프레임을 SQLite 데이터베이스에 저장
df.to_sql(name='ticker_data', con=con, if_exists='replace', index=False)

# 연결 종료
con.close()

print("데이터프레임이 SQLite 데이터베이스에 저장되었습니다.")

데이터프레임이 SQLite 데이터베이스에 저장되었습니다.

In [52]:
# 시간대별 통계
stats = df.groupby(['hour', 'minute']).agg({
    'volatility': 'mean',
    'success': 'mean',
    'next_return': 'mean',
    'target': 'count'
}).round(4)
stats

              volatility  success  next_return  target
hour minute
0    0       178800.3055   0.4563       0.0001    2619
     15      164157.3120   0.4032       0.0001    2619
     30      163257.2519   0.4195       0.0002    2620
     45      149277.8626   0.4050       0.0001    2620
1    0       173588.0107   0.5116       0.0000    2619
...                  ...      ...          ...     ...
22   45      182954.6148   0.3955       0.0000    2622
23   0       183459.7789   0.4403       0.0000    2623
     15      168558.1395   0.3885      -0.0000    2623
     30      184187.3331   0.4414      -0.0002    2621
     45      166144.3299   0.3704       0.0001    2619

[96 rows x 4 columns]

In [54]:
df['success'].value_counts()

success
0    145441
1    105982
Name: count, dtype: int64

In [53]:
stats.to_csv('시간대별통계.csv', index=True)

In [ ]:
analyze_optimal_trading_time(df_sorted)